name: tbd-env
channels:
 - conda-forge
 - pytorch
dependencies:
  - python=3.6
  - numpy=1.13
  - matplotlib=2.0
  - h5py=2.7
  - pathlib2=2.3
  - scipy=0.19.1
  - Pillow=8.4.0
  - jupyter=1.0.0
  - torchvision
  - pytorch